version: "3"

services:
  client:
    container_name: rotang_client
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - rotang_network
    env_file:
      - .env.production
networks:
  rotang_network:
    external: true
