import { Footer, Header, Sidebar } from "@/app/shared/components/layout";
import { getCollections } from "@/app/shared/service";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const collections = await getCollections();

  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="min-h-screen w-full bg-gray-100 text-gray-700 overflow-hidden" x-data="layout">
          <Header />
          <div className="flex min-h-screen pt-14">
            <Sidebar list={collections} />
            {children}
          </div>
          <Footer />
        </main>
      </body>
    </html>
  );
}
