version: "3"

services:
  api:
    container_name: rotang_api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 7500:7500
    networks:
      - rotang_network
    volumes:
      - ./upload:/app/upload
    env_file:
      - .env
networks:
  rotang_network:
    external: true
